In [27]:
import yake
import spacy
from itertools import combinations

In [248]:
text2="The story is about a young man named Servigny who is in love with a young woman named Yvette. Servigny is a wealthy man and he is very attracted to Yvette's beauty and her carefree attitude. Yvette, on the other hand, is not interested in Servigny and she does not want to get married. She enjoys her life as a courtesan and she does not want to give that up. Servigny and Yvette spend a lot of time together and they eventually fall in love. However, their relationship is doomed because Yvette does not want to get married. Servigny is heartbroken and he eventually leaves Yvette."

In [6]:
text_full='''As they were leaving the Cafe Riche, Jean de Servigny said to Leon
Saval: "If you don't object, let us walk. The weather is too fine to
take a cab."

His friend answered: "I would like nothing better."

Jean replied: "It is hardly eleven o'clock. We shall arrive much
before midnight, so let us go slowly."

A restless crowd was moving along the boulevard, that throng
peculiar to summer nights, drinking, chatting, and flowing like a
river, filled with a sense of comfort and joy. Here and there a cafe
threw a flood of light upon a knot of patrons drinking at little
tables on the sidewalk, which were covered with bottles and glasses,
hindering the passing of the hurrying multitude. On the pavement the
cabs with their red, blue, or green lights dashed by, showing for a
second, in the glimmer, the thin shadow of the horse, the raised
profile of the coachman, and the dark box of the carriage. The cabs
of the Urbaine Company made clear and rapid spots when their yellow
panels were struck by the light.

The two friends walked with slow steps, cigars in their mouths, in
evening dress and overcoats on their arms, with a flower in their
buttonholes, and their hats a trifle on one side, as men will
carelessly wear them sometimes, after they have dined well and the
air is mild.

They had been linked together since their college days by a close,
devoted, and firm affection. Jean de Servigny, small, slender, a
trifle bald, rather frail, with elegance of mien, curled mustache,
bright eyes, and fine lips, was a man who seemed born and bred upon
the boulevard. He was tireless in spite of his languid air, strong
in spite of his pallor, one of those slight Parisians to whom
gymnastic exercise, fencing, cold shower and hot baths give a
nervous, artificial strength. He was known by his marriage as well
as by his wit, his fortune, his connections, and by that
sociability, amiability, and fashionable gallantry peculiar to
certain men.

A true Parisian, furthermore, light, sceptical, changeable,
captivating, energetic, and irresolute, capable of everything and of
nothing; selfish by principle and generous on occasion, he lived
moderately upon his income, and amused himself with hygiene.
Indifferent and passionate, he gave himself rein and drew back
constantly, impelled by conflicting instincts, yielding to all, and
then obeying, in the end, his own shrewd man-about-town judgment,
whose weather-vane logic consisted in following the wind and drawing
profit from circumstances without taking the trouble to originate
them.

His companion, Leon Saval, rich also, was one of those superb and
colossal figures who make women turn around in the streets to look
at them. He gave the idea of a statue turned into a man, a type of a
race, like those sculptured forms which are sent to the Salons. Too
handsome, too tall, too big, too strong, he sinned a little from the
excess of everything, the excess of his qualities. He had on hand
countless affairs of passion.

As they reached the Vaudeville theater, he asked: "Have you warned
that lady that you are going to take me to her house to see her?"

Servigny began to laugh: "Forewarn the Marquise Obardi! Do you warn
an omnibus driver that you shall enter his stage at the corner of
the boulevard?"

Saval, a little perplexed, inquired: "What sort of person is this
lady?"

His friend replied: "An upstart, a charming hussy, who came from no
one knows where, who made her appearance one day, nobody knows how,
among the adventuresses of Paris, knowing perfectly well how to take
care of herself. Besides, what difference does it make to us? They
say that her real name, her maiden name--for she still has every
claim to the title of maiden except that of innocence--is Octavia
Bardin, from which she constructs the name Obardi by prefixing the
first letter of her first name and dropping the last letter of the
last name."

"Moreover, she is a lovable woman, and you, from your physique, are
inevitably bound to become her lover. Hercules is not introduced
into Messalina's home without making some disturbance. Nevertheless
I make bold to add that if there is free entrance to this house,
just as there is in bazaars, you are not exactly compelled to buy
what is for sale. Love and cards are on the programme, but nobody
compels you to take up with either. And the exit is as free as the
entrance."

"She settled down in the Etoile district, a suspicious neighborhood,
three years ago, and opened her drawing-room to that froth of the
continents which comes to Paris to practice its various formidable
and criminal talents."

"I don't remember just how I went to her house. I went as we all go,
because there is card playing, because the women are compliant, and
the men dishonest. I love that social mob of buccaneers with
decorations of all sorts of orders, all titled, and all entirely
unknown at their embassies, except to the spies. They are always
dragging in the subject of honor, quoting the list of their
ancestors on the slightest provocation, and telling the story of
their life at every opportunity, braggarts, liars, sharpers,
dangerous as their cards, false as their names, brave because they
have to be, like the assassins who can not pluck their victims
except by exposing their own lives. In a word, it is the aristocracy
of the bagnio."

"I like them. They are interesting to fathom and to know, amusing to
listen to, often witty, never commonplace as the ordinary French
guests. Their women are always pretty, with a little flavor of
foreign knavery, with the mystery of their past existence, half of
which, perhaps, spent in a House of Correction. They generally have
fine eyes and glorious hair, the true physique of the profession, an
intoxicating grace, a seductiveness which drives men to folly, an
unwholesome, irresistible charm! They conquer like the highwaymen of
old. They are rapacious creatures; true birds of prey. I like them,
too."

"The Marquise Obardi is one of the type of these elegant
good-for-nothings. Ripe and pretty, with a feline charm, you can see
that she is vicious to the marrow. Everybody has a good time at her
house, with cards, dancing, and suppers; in fact there is everything
which goes to make up the pleasures of fashionable society life."

"Have you ever been or are you now her lover?" Leon Saval asked.

"I have not been her lover, I am not now, and I never shall be. I
only go to the house to see her daughter."

"Ah! She has a daughter, then?"

"A daughter! A marvel, my dear man. She is the principal attraction
of the den to-day. Tall, magnificent, just ripe, eighteen years old,
as fair as her mother is dark, always merry, always ready for an
entertainment, always laughing, and ready to dance like mad. Who
will be the lucky man, to capture her, or who has already done so?
Nobody can tell that. She has ten of us in her train, all hoping."

"Such a daughter in the hands of a woman like the Marquise is a
fortune. And they play the game together, the two charmers. No one
knows just what they are planning. Perhaps they are waiting for a
better bargain than I should prove. But I tell you that I shall
close the bargain if I ever get a chance."

"That girl Yvette absolutely baffles me, moreover. She is a mystery.
If she is not the most complete monster of astuteness and perversity
that I have ever seen, she certainly is the most marvelous
phenomenon of innocence that can be imagined. She lives in that
atmosphere of infamy with a calm and triumphing ease which is either
wonderfully profligate or entirely artless. Strange scion of an
adventuress, cast upon the muck-heap of that set, like a magnificent
plant nurtured upon corruption, or rather like the daughter of some
noble race, of some great artist, or of some grand lord, of some
prince or dethroned king, tossed some evening into her mother's
arms, nobody can make out what she is nor what she thinks. But you
are going to see her."

Saval began to laugh and said: "You are in love with her."

"No. I am on the list, which is not precisely the same thing. I will
introduce you to my most serious rivals. But the chances are in my
favor. I am in the lead, and some little distinction is shown to
me."

"You are in love," Saval repeated.

"No. She disquiets me, seduces and disturbs me, attracts and
frightens me away. I mistrust her as I would a trap, and I long for
her as I long for a sherbet when I am thirsty. I yield to her charm,
and I only approach her with the apprehension that I would feel
concerning a man who was known to be a skillful thief. To her
presence I have an irrational impulse toward belief in her possible
purity and a very reasonable mistrust of her not less probable
trickery. I feel myself in contact with an abnormal being, beyond
the pale of natural laws, an exquisite or detestable creature--I
don't know which."

For the third time Saval said: "I tell you that you are in love. You
speak of her with the magniloquence of a poet and the feeling of a
troubadour. Come, search your heart, and confess."

Servigny walked a few steps without answering. Then he replied:

"That is possible, after all. In any case, she fills my mind almost
continually. Yes, perhaps I am in love. I dream about her too much.
I think of her when I am asleep and when I awake--that is surely a
grave indication. Her face follows me, accompanies me ceaselessly,
ever before me, around me, with me. Is this love, this physical
infatuation? Her features are so stamped upon my vision that I see
her the moment I shut my eyes. My heart beats quickly every time I
look at her, I don't deny it."

"So I am in love with her, but in a queer fashion. I have the
strongest desire for her, and yet the idea of making her my wife
would seem to me a folly, a piece of stupidity, a monstrous thing:
And I have a little fear of her, as well, the fear which a bird
feels over which a hawk is hovering."

"And again I am jealous of her, jealous of all of which I am
ignorant in her incomprehensible heart. I am always wondering: 'Is
she a charming youngster or a wretched jade?' She says things that
would make an army shudder; but so does a parrot. She is at times so
indiscreet and yet modest that I am forced to believe in her
spotless purity, and again so incredibly artless that I must suspect
that she has never been chaste. She allures me, excites me, like a
woman of a certain category, and at the same time acts like an
impeccable virgin. She seems to love me and yet makes fun of me; she
deports herself in public as if she were my mistress and treats me
in private as if I were her brother or footman."

"There are times when I fancy that she has as many lovers as her
mother. And at other times I imagine that she suspects absolutely
nothing of that sort of life, you understand. Furthermore, she is a
great novel reader. I am at present, while awaiting something
better, her book purveyor. She calls me her 'librarian.' Every week
the New Book Store sends her, on my orders, everything new that has
appeared, and I believe that she reads everything at random. It must
make a strange sort of mixture in her head."

"That kind of literary hasty-pudding accounts perhaps for some of
the girl's peculiar ways. When a young woman looks at existence
through the medium of fifteen thousand novels, she must see it in a
strange light, and construct queer ideas about matters and things in
general. As for me, I am waiting. It is certain at any rate that I
never have had for any other woman the devotion which I have had for
her. And still it is quite certain that I shall never marry her. So
if she has had numbers, I shall swell the number. And if she has
not, I shall take the first ticket, just as I would do for a street
car."

"The case is very simple. Of course, she will never marry. Who in
the world would marry the Marquise Obardi's daughter, the child of
Octavia Bardin? Nobody, for a thousand reasons. Where would they
ever find a husband for her? In society? Never. The mother's house
is a sort of liberty-hall whose patronage is attracted by the
daughter. Girls don't get married under those conditions."

"Would she find a husband among the trades-people? Still less would
that be possible. And besides the Marquise is not the woman to make
a bad bargain; she will give Yvette only to a man of high position,
and that man she will never discover."

"Then perhaps she will look among the common people. Still less
likely. There is no solution of the problem, then. This young lady
belongs neither to society, nor to the tradesmen's class, nor to the
common people, and she can never enter any of these ranks by
marriage."

"She belongs through her mother, her birth, her education, her
inheritance, her manners, and her customs, to the vortex of the most
rapid life of Paris. She can never escape it, save by becoming a
nun, which is not at all probable with her manners and tastes. She
has only one possible career, a life of pleasure. She will come to
it sooner or later, if indeed she has not already begun to tread its
primrose path. She cannot escape her fate. From being a young girl
she will take the inevitable step, quite simply. And I would like to
be the pivot of this transformation."

"I am waiting. There are many lovers. You will see among them a
Frenchman, Monsieur de Belvigne; a Russian, called Prince Kravalow,
and an Italian, Chevalier Valreali, who have all announced their
candidacies and who are consequently maneuvering to the best of
their ability. In addition to these there are several freebooters of
less importance. The Marquise waits and watches. But I think that
she has views about me. She knows that I am very rich, and she makes
less of the others."

"Her drawing-room is, moreover, the most astounding that I know of,
in such, exhibitions. You even meet very decent men there, like
ourselves. As for the women, she has culled the best there is from
the basket of pickpockets. Nobody knows where she found them. It is
a set apart from Bohemia, apart from everything. She has had one
inspiration showing genius, and that is the knack of selecting
especially those adventuresses who have children, generally girls.
So that a fool might believe that in her house he was among
respectable women!" They had reached the avenue of the Champs-Elysees.
A gentle breeze softly stirred the leaves and touched the faces of
passers-by, like the breaths of a giant fan, waving somewhere in
the sky. Silent shadows wandered beneath the trees; others, on
benches, made a dark spot. And these shadows spoke very low, as if
they were telling each other important or shameful secrets.

"You can't imagine what a collection of fictitious titles are met in
this lair," said Servigny, "By the way, I shall present you by the
name of Count Saval; plain Saval would not do at all."

"Oh, no, indeed!" cried his friend; "I would not have anyone think
me capable of borrowing a title, even for an evening, even among
those people. Ah, no!"

Servigny began to laugh.

"How stupid you are! Why, in that set they call me the Duke de
Servigny. I don't know how nor why. But at any rate the Duke de
Servigny I am and shall remain, without complaining or protesting.
It does not worry me. I should have no footing there whatever
without a title."

But Saval would not be convinced.

"Well, you are of rank, and so you may remain. But, as for me, no. I
shall be the only common person in the drawing-room. So much the
worse, or, so much the better. It will be my mark of distinction and
superiority."

Servigny was obstinate.

"I tell you that it is not possible. Why, it would almost seem
monstrous. You would have the effect of a ragman at a meeting of
emperors. Let me do as I like. I shall introduce you as the Vice-Roi
du 'Haut-Mississippi,' and no one will be at all astonished. When a
man takes on greatness, he can't take too much."

"Once more, no, I do not wish it."

"Very well, have your way. But, in fact, I am very foolish to try to
convince you. I defy you to get in without some one giving you a
title, just as they give a bunch of violets to the ladies at the
entrance to certain stores."

They turned to the right in the Rue de Barrie, mounted one flight of
stairs in a fine modern house, and gave their overcoats and canes
into the hands of four servants in knee-breeches. A warm odor, as of
a festival assembly, filled the air, an odor of flowers, perfumes,
and women; and a composed and continuous murmur came from the
adjoining rooms, which were filled with people.

A kind of master of ceremonies, tall, erect, wide of girth, serious,
his face framed in white whiskers, approached the newcomers, asking
with a short and haughty bow: "Whom shall I announce?"

"Monsieur Saval," Servigny replied.

Then with a loud voice, the man opening the door cried out to the
crowd of guests:

"Monsieur the Duke de Servigny."

"Monsieur the Baron Saval."

The first drawing-room was filled with women. The first thing which
attracted attention was the display of bare shoulders, above a flood
of brilliant gowns.

The mistress of the house who stood talking with three friends,
turned and came forward with a majestic step, with grace in her mien
and a smile on her lips. Her forehead was narrow and very low, and
was covered with a mass of glossy black hair, encroaching a little
upon the temples.

She was tall, a trifle too large, a little too stout, over ripe, but
very pretty, with a heavy, warm, potent beauty. Beneath that mass of
hair, full of dreams and smiles, rendering her mysteriously
captivating, were enormous black eyes. Her nose was a little narrow,
her mouth large and infinitely seductive, made to speak and to
conquer.

Her greatest charm was in her voice. It came from that mouth as
water from a spring, so natural, so light, so well modulated, so
clear, that there was a physical pleasure in listening to it. It was
a joy for the ear to hear the flexible words flow with the grace of
a babbling brook, and it was a joy for the eyes to see those pretty
lips, a trifle too red, open as the words rippled forth.

She gave one hand to Servigny, who kissed it, and dropping her fan
on its little gold chain, she gave the other to Saval, saying to
him: "You are welcome, Baron, all the Duke's friends are at home
here."

Then she fixed her brilliant eyes upon the Colossus who had just
been introduced to her. She had just the slightest down on her upper
lip, a suspicion of a mustache, which seemed darker when she spoke.
There was a pleasant odor about her, pervading, intoxicating, some
perfume of America or of the Indies. Other people came in,
marquesses, counts or princes. She said to Servigny, with the
graciousness of a mother: "You will find my daughter in the other
parlor. Have a good time, gentlemen, the house is yours."

And she left them to go to those who had come later, throwing at
Saval that smiling and fleeting glance which women use to show that
they are pleased. Servigny grasped his friend's arm.

"I will pilot you," said he. "In this parlor where we now are,
women, the temples of the fleshly, fresh or otherwise. Bargains as
good as new, even better, for sale or on lease. At the right,
gaming, the temple of money. You understand all about that. At the
lower end, dancing, the temple of innocence, the sanctuary, the
market for young girls. They are shown off there in every light.
Even legitimate marriages are tolerated. It is the future, the hope,
of our evenings. And the most curious part of this museum of moral
diseases are these young girls whose souls are out of joint, just
like the limbs of the little clowns born of mountebanks. Come and
look at them."

He bowed, right and left, courteously, a compliment on his lips,
sweeping each low-gowned woman whom he knew with the look of an
expert.

The musicians, at the end of the second parlor, were playing a
waltz; and the two friends stopped at the door to look at them. A
score of couples were whirling-the men with a serious expression,
and the women with a fixed smile on their lips. They displayed a
good deal of shoulder, like their mothers; and the bodices of some
were only held in place by a slender ribbon, disclosing at times
more than is generally shown.

Suddenly from the end of the room a tall girl darted forward,
gliding through the crowd, brushing against the dancers, and holding
her long train in her left hand. She ran with quick little steps as
women do in crowds, and called out: "Ah! How is Muscade? How do you
do, Muscade?"

Her features wore an expression of the bloom of life, the
illumination of happiness. Her white flesh seemed to shine, the
golden-white flesh which goes with red hair. The mass of her
tresses, twisted on her head, fiery, flaming locks, nestled against
her supple neck, which was still a little thin.

She seemed to move just as her mother was made to speak, so natural,
noble, and simple were her gestures. A person felt a moral joy and
physical pleasure in seeing her walk, stir about, bend her head, or
lift her arm. "Ah! Muscade, how do you do, Muscade?" she repeated.

Servigny shook her hand violently, as he would a man's, and said:
"Mademoiselle Yvette, my friend, Baron Saval."

"Good evening, Monsieur. Are you always as tall as that?"

Servigny replied in that bantering tone which he always used with
her, in order to conceal his mistrust and his uncertainty:

"No, Mam'zelle. He has put on his greatest dimensions to please your
mother, who loves a colossus."

And the young girl remarked with a comic seriousness: "Very well But
when you come to see me you must diminish a little if you please. I
prefer the medium height. Now Muscade has just the proportions which
I like."

And she gave her hand to the newcomer. Then she asked: "Do you
dance, Muscade? Come, let us waltz." Without replying, with a quick
movement, passionately, Servigny clasped her waist and they
disappeared with the fury of a whirlwind.

They danced more rapidly than any of the others, whirled and
whirled, and turned madly, so close together that they seemed but
one, and with the form erect, the legs almost motionless, as if some
invisible mechanism, concealed beneath their feet, caused them to
twirl. They appeared tireless. The other dancers stopped from time
to time. They still danced on, alone. They seemed not to know where
they were nor what they were doing, as if, they had gone far away
from the ball, in an ecstasy. The musicians continued to play, with
their looks fixed upon this mad couple; all the guests gazed at
them, and when finally they did stop dancing, everyone applauded
them.

She was a little flushed, with strange eyes, ardent and timid, less
daring than a moment before, troubled eyes, blue, yet with a pupil
so black that they seemed hardly natural. Servigny appeared giddy.
He leaned against a door to regain his composure.

"You have no head, my poor Muscade, I am steadier than you," said
Yvette to Servigny. He smiled nervously, and devoured her with a
look. His animal feelings revealed themselves in his eyes and in the
curl of his lips. She stood beside him looking down, and her bosom
rose and fell in short gasps as he looked at her.

Then she said softly: "Really, there are times when you are like a
tiger about to spring upon his prey. Come, give me your arm, and let
us find your friend."

Silently he offered her his arm and they went down the long drawing-room
together.

Saval was not alone, for the Marquise Obardi had rejoined him. She
conversed with him on ordinary and fashionable subjects with a
seductiveness in her tones which intoxicated him. And, looking at
her with his mental eye, it seemed to him that her lips, uttered
words far different from those which they formed. When she saw
Servigny her face immediately lighted up, and turning toward him she
said:

"You know, my dear Duke, that I have just leased a villa at Bougival
for two months, and I count upon your coming to see me there, and
upon your friend also. Listen. We take possession next Monday, and
shall expect both of you to dinner the following Saturday. We shall
keep you over Sunday."

Perfectly serene and tranquil Yvette smiled, saying with a decision
which swept away hesitation on his part:

"Of course Muscade will come to dinner on Saturday. We have only to
ask him, for he and I intend to commit a lot of follies in the
country."

He thought he divined the birth of a promise in her smile, and in
her voice he heard what he thought was invitation.

Then the Marquise turned her big, black eyes upon Saval: "And you
will, of course, come, Baron?"

With a smile that forbade doubt, he bent toward her, saying, "I
shall be only too charmed, Madame."

Then Yvette murmured with malice that was either naive or
traitorous: "We will set all the world by the ears down there, won't
we, Muscade, and make my regiment of admirers fairly mad." And with
a look, she pointed out a group of men who were looking at them from
a little distance.

Said Servigny to her: "As many follies as YOU may please,
Mam'zelle."

In speaking to Yvette, Servigny never used the word "Mademoiselle,"
by reason of his close and long intimacy with her.

Then Saval asked: "Why does Mademoiselle always call my friend
Servigny 'Muscade'?"

Yvette assumed a very frank air and said:

"I will tell you: It is because he always slips through my hands.
Now I think I have him, and then I find I have not."

The Marquise, with her eyes upon Saval, arid evidently preoccupied,
said in a careless tone: "You children are very funny."

But Yvette bridled up: "I do not intend to be funny; I am simply
frank. Muscade pleases me, and is always deserting me, and that is
what annoys me."

Servigny bowed profoundly, saying: "I will never leave you any more,
Mam'zelle, neither day nor night." She made a gesture of horror:

"My goodness! no--what do you mean? You are all right during the
day, but at night you might embarrass me."

With an air of impertinence he asked: "And why?"

Yvette responded calmly and audaciously, "Because you would not look
well en deshabille."

The Marquise, without appearing at all disturbed, said: "What
extraordinary subjects for conversation. One would think that you
were not at all ignorant of such things."

And Servigny jokingly added: "That is also my opinion, Marquise."

Yvette turned her eyes upon him, and in a haughty, yet wounded, tone
said: "You are becoming very vulgar--just as you have been several
times lately." And turning quickly she appealed to an individual
standing by:

"Chevalier, come and defend me from insult."

A thin, brown man, with an easy carriage, came forward.

"Who is the culprit?" said he, with a constrained smile.

Yvette pointed out Servigny with a nod of her head:

"There he is, but I like him better than I do you, because he is
less of a bore."

The Chevalier Valreali bowed:

"I do what I can, Mademoiselle. I may have less ability, but not
less devotion."

A gentleman came forward, tall and stout, with gray whiskers, saying
in loud tones: "Mademoiselle Yvette, I am your most devoted slave."

Yvette cried: "Ah, Monsieur de Belvigne." Then turning toward Saval,
she introduced him.

"My last adorer--big, fat, rich, and stupid. Those are the kind I
like. A veritable drum-major--but of the table d'hote. But see, you
are still bigger than he. How shall I nickname you? Good! I have it.
I shall call you 'M. Colossus of Rhodes, Junior,' from the Colossus
who certainly was your father. But you two ought to have very
interesting things to say to each other up there, above the heads of
us all--so, by-bye."

And she left them quickly, going to the orchestra to make the
musicians strike up a quadrille.

Madame Obardi seemed preoccupied. In a soft voice she said to
Servigny:

"You are always teasing her. You will warp her character and bring
out many bad traits."

Servigny replies: "Why, haven't you finished her education?"

She appeared not to understand, and continued talking in a friendly
way. But she noticed a solemn looking man, wearing a perfect
constellation of crosses and orders, standing near her, and she ran
to him:

"Ah Prince, Prince, what good fortune!"

Servigny took Saval's arm and drew him away:

"That is the latest serious suitor, Prince Kravalow. Isn't she
superb?"

"To my mind they are both superb. The mother would suffice for me
perfectly," answered Saval.

Servigny nodded and said: "At your disposal, my dear boy."

The dancers elbowed them aside, as they were forming for a
quadrille.

"Now let us go and see the sharpers," said Servigny. And they
entered the gambling-room.

Around each table stood a group of men, looking on. There was very
little conversation. At times the clink of gold coins, tossed upon
the green cloth or hastily seized, added its sound to the murmur of
the players, just as if the money was putting in its word among the
human voices.

All the men were decorated with various orders, and odd ribbons, and
they all wore the same severe expression, with different
countenances. The especially distinguishing feature was the beard.

The stiff American with his horseshoe, the haughty Englishman with
his fan-beard open on his breast, the Spaniard with his black fleece
reaching to the eyes, the Roman with that huge mustache which Italy
copied from Victor Emmanuel, the Austrian with his whiskers and
shaved chin, a Russian general whose lip seemed armed with two
twisted lances, and a Frenchman with a dainty mustache, displayed
the fancies of all the barbers in the world.

"You won't join the game?" asked Servigny.

"No, shall you?"

"Not now. If you are ready to go, we will come back some quieter
day. There are too many people here to-day, and we can't do
anything."

"Well, let us go."

And they disappeared behind a door-curtain into the hall. As soon as
they were in the street Servigny asked: "Well, what do you think of
it?"

"It certainly is interesting, but I fancy the women's side of it
more than the men's."

"Indeed! Those women are the best of the tribe for us. Don't you
find that you breathe the odor of love among them, just as you scent
the perfumes at a hairdresser's?"

"Really such houses are the place for one to go. And what experts,
my dear fellow! What artists! Have you ever eaten bakers' cakes?
They look well, but they amount to nothing. The man who bakes them
only knows how to make bread. Well! the love of a woman in ordinary
society always reminds me of these bake-shop trifles, while the love
you find at houses like the Marquise Obardi's, don't you see, is the
real sweetmeat. Oh! they know how to make cakes, these charming
pastry-cooks. Only you pay five sous, at their shops, for what costs
two sous elsewhere."

"Who is the master of the house just now?" asked Saval.

Servigny shrugged his shoulders, signifying his ignorance.

"I don't know, the latest one known was an English peer, but he left
three months ago. At present she must live off the common herd, or
the gambling, perhaps, and on the gamblers, for she has her
caprices. But tell me, it is understood that we dine with her on
Saturday at Bougival, is it not? People are more free in the
country, and I shall succeed in finding out what ideas Yvette has in
her head!"

"I should like nothing better," replied Saval. "I have nothing to do
that day."

Passing down through the Champs-Elysees, under the steps they
disturbed a couple making love on one of the benches, and Servigny
muttered: "What foolishness and what a serious matter at the same
time! How commonplace and amusing love is, always the same and
always different! And the beggar who gives his sweetheart twenty
sous gets as much return as I would for ten thousand francs from
some Obardi, no younger and no less stupid perhaps than this
nondescript. What nonsense!"

He said nothing for a few minutes; then he began again: "All the
same, it would be good to become Yvette's first lover. Oh! for that
I would give--"

He did not add what he would give, and Saval said good night to him
as they reached the corner of the Rue Royale.'''

In [44]:
text="I There are houses in certain provincial towns whose aspect inspires melancholy, akin to that called forth by sombre cloisters, dreary moorlands, or the desolation of ruins. Within these houses there is, perhaps, the silence of the cloister, the barrenness of moors, the skeleton of ruins; life and movement are so stagnant there that a stranger might think them uninhabited, were it not that he encounters suddenly the pale, cold glance of a motionless person, whose half-monastic face peers beyond the window-casing at the sound of an unaccustomed step. Such elements of sadness formed the physiognomy, as it were, of a dwelling-house in Saumur which stands at the end of the steep street leading to the chateau in the upper part of the town. This street--now little frequented, hot in summer, cold in winter, dark in certain sections--is remarkable for the resonance of its little pebbly pavement, always clean and dry, for the narrowness of its tortuous road-way, for the peaceful stillness of its houses, which belong to the Old town and are over-topped by the ramparts. Houses three centuries old are still solid, though built of wood, and their divers aspects add to the originality which commends this portion of Saumur to the attention of artists and antiquaries. It is difficult to pass these houses without admiring the enormous oaken beams, their ends carved into fantastic figures, which crown with a black bas-relief the lower floor of most of them. In one place these transverse timbers are covered with slate and mark a bluish line along the frail wall of a dwelling covered by a roof _en colombage_ which bends beneath the weight of years, and whose rotting shingles are twisted by the alternate action of sun and rain. In another place blackened, worn-out window-sills, with delicate sculptures now scarcely discernible, seem too weak to bear the brown clay pots from which springs the heart’s-ease or the rose-bush of some poor working-woman. Farther on are doors studded with enormous nails, where the genius of our forefathers has traced domestic hieroglyphics, of which the meaning is now lost forever. Here a Protestant attested his belief; there a Leaguer cursed Henry IV.; elsewhere some bourgeois has carved the insignia of his _noblesse de cloches_, symbols of his long-forgotten magisterial glory. The whole history of France is there. Next to a tottering house with roughly plastered walls, where an artisan enshrines his tools, rises the mansion of a country gentleman, on the stone arch of which above the door vestiges of armorial bearings may still be seen, battered by the many revolutions that have shaken France since 1789. In this hilly street the ground-floors of the merchants are neither shops nor warehouses; lovers of the Middle Ages will here find the _ouvrouere_ of our forefathers in all its naive simplicity. These low rooms, which have no shop-frontage, no show-windows, in fact no glass at all, are deep and dark and without interior or exterior decoration. Their doors open in two parts, each roughly iron-bound; the upper half is fastened back within the room, the lower half, fitted with a spring-bell, swings continually to and fro. Air and light reach the damp den within, either through the upper half of the door, or through an open space between the ceiling and a low front wall, breast-high, which is closed by solid shutters that are taken down every morning, put up every evening, and held in place by heavy iron bars. This wall serves as a counter for the merchandise. No delusive display is there; only samples of the business, whatever it may chance to be,--such, for instance, as three or four tubs full of codfish and salt, a few bundles of sail-cloth, cordage, copper wire hanging from the joists above, iron hoops for casks ranged along the wall, or a few pieces of cloth upon the shelves. Enter. A neat girl, glowing with youth, wearing a white kerchief, her arms red and bare, drops her knitting and calls her father or her mother, one of whom comes forward and sells you what you want, phlegmatically, civilly, or arrogantly, according to his or her individual character, whether it be a matter of two sous’ or twenty thousand francs’ worth of merchandise. You may see a cooper, for instance, sitting in his doorway and twirling his thumbs as he talks with a neighbor. To all appearance he owns nothing more than a few miserable boat-ribs and two or three bundles of laths; but below in the port his teeming wood-yard supplies all the cooperage trade of Anjou. He knows to a plank how many casks are needed if the vintage is good. A hot season makes him rich, a rainy season ruins him; in a single morning puncheons worth eleven francs have been known to drop to six. In this country, as in Touraine, atmospheric vicissitudes control commercial life. Wine-growers, proprietors, wood-merchants, coopers, inn-keepers, mariners, all keep watch of the sun. They tremble when they go to bed lest they should hear in the morning of a frost in the night; they dread rain, wind, drought, and want water, heat, and clouds to suit their fancy. A perpetual duel goes on between the heavens and their terrestrial interests. The barometer smooths, saddens, or makes merry their countenances, turn and turn about. From end to end of this street, formerly the Grand’Rue de Saumur, the words: “Here’s golden weather,” are passed from door to door; or each man calls to his neighbor: “It rains louis,” knowing well what a sunbeam or the opportune rainfall is bringing him. On Saturdays after midday, in the fine season, not one sou’s worth of merchandise can be bought from these worthy traders. Each has his vineyard, his enclosure of fields, and all spend two days in the country. This being foreseen, and purchases, sales, and profits provided for, the merchants have ten or twelve hours to spend in parties of pleasure, in making observations, in criticisms, and in continual spying. A housewife cannot buy a partridge without the neighbors asking the husband if it were cooked to a turn. A young girl never puts her head near a window that she is not seen by idling groups in the street. Consciences are held in the light; and the houses, dark, silent, impenetrable as they seem, hide no mysteries. Life is almost wholly in the open air; every household sits at its own threshold, breakfasts, dines, and quarrels there. No one can pass along the street without being examined; in fact formerly, when a stranger entered a provincial town he was bantered and made game of from door to door. From this came many good stories, and the nickname _copieux_, which was applied to the inhabitants of Angers, who excelled in such urban sarcasms. The ancient mansions of the old town of Saumur are at the top of this hilly street, and were formerly occupied by the nobility of the neighborhood. The melancholy dwelling where the events of the following history took place is one of these mansions,--venerable relics of a century in which men and things bore the characteristics of simplicity which French manners and customs are losing day by day. Follow the windings of the picturesque thoroughfare, whose irregularities awaken recollections that plunge the mind mechanically into reverie, and you will see a somewhat dark recess, in the centre of which is hidden the door of the house of Monsieur Grandet. It is impossible to understand the force of this provincial expression--the house of Monsieur Grandet--without giving the biography of Monsieur Grandet himself. Monsieur Grandet enjoyed a reputation in Saumur whose causes and effects can never be fully understood by those who have not, at one time or another, lived in the provinces. In 1789 Monsieur Grandet--still called by certain persons le Pere Grandet, though the number of such old persons has perceptibly diminished--was a master-cooper, able to read, write, and cipher. At the period when the French Republic offered for sale the church property in the arrondissement of Saumur, the cooper, then forty years of age, had just married the daughter of a rich wood-merchant. Supplied with the ready money of his own fortune and his wife’s _dot_, in all about two thousand louis-d’or, Grandet went to the newly established “district,” where, with the help of two hundred double louis given by his father-in-law to the surly republican who presided over the sales of the national domain, he obtained for a song, legally if not legitimately, one of the finest vineyards in the arrondissement, an old abbey, and several farms. The inhabitants of Saumur were so little revolutionary that they thought Pere Grandet a bold man, a republican, and a patriot with a mind open to all the new ideas; though in point of fact it was open only to vineyards. He was appointed a member of the administration of Saumur, and his pacific influence made itself felt politically and commercially. Politically, he protected the ci-devant nobles, and prevented, to the extent of his power, the sale of the lands and property of the _emigres_; commercially, he furnished the Republican armies with two or three thousand puncheons of white wine, and took his pay in splendid fields belonging to a community of women whose lands had been reserved for the last lot. Under the Consulate Grandet became mayor, governed wisely, and harvested still better pickings. Under the Empire he was called Monsieur Grandet. Napoleon, however, did not like republicans, and superseded Monsieur Grandet (who was supposed to have worn the Phrygian cap) by a man of his own surroundings, a future baron of the Empire. Monsieur Grandet quitted office without regret. He had constructed in the interests of the town certain fine roads which led to his own property; his house and lands, very advantageously assessed, paid moderate taxes; and since the registration of his various estates, the vineyards, thanks to his constant care, had become the “head of the country,”--a local term used to denote those that produced the finest quality of wine. He might have asked for the cross of the Legion of honor. This event occurred in 1806. Monsieur Grandet was then fifty-seven years of age, his wife thirty-six, and an only daughter, the fruit of their legitimate love, was ten years old. Monsieur Grandet, whom Providence no doubt desired to compensate for the loss of his municipal honors, inherited three fortunes in the course of this year,--that of Madame de la Gaudiniere, born de la Bertelliere, the mother of Madame Grandet; that of old Monsieur de la Bertelliere, her grandfather; and, lastly, that of Madame Gentillet, her grandmother on the mother’s side: three inheritances, whose amount was not known to any one. The avarice of the deceased persons was so keen that for a long time they had hoarded their money for the pleasure of secretly looking at it. Old Monsieur de la Bertelliere called an investment an extravagance, and thought he got better interest from the sight of his gold than from the profits of usury. The inhabitants of Saumur consequently estimated his savings according to “the revenues of the sun’s wealth,” as they said. Monsieur Grandet thus obtained that modern title of nobility which our mania for equality can never rub out. He became the most imposing personage in the arrondissement. He worked a hundred acres of vineyard, which in fruitful years yielded seven or eight hundred hogsheads of wine. He owned thirteen farms, an old abbey, whose windows and arches he had walled up for the sake of economy,--a measure which preserved them,--also a hundred and twenty-seven acres of meadow-land, where three thousand poplars, planted in 1793, grew and flourished; and finally, the house in which he lived. Such was his visible estate; as to his other property, only two persons could give even a vague guess at its value: one was Monsieur Cruchot, a notary employed in the usurious investments of Monsieur Grandet; the other was Monsieur des Grassins, the richest banker in Saumur, in whose profits Grandet had a certain covenanted and secret share. Although old Cruchot and Monsieur des Grassins were both gifted with the deep discretion which wealth and trust beget in the provinces, they publicly testified so much respect to Monsieur Grandet that observers estimated the amount of his property by the obsequious attention which they bestowed upon him. In all Saumur there was no one not persuaded that Monsieur Grandet had a private treasure, some hiding-place full of louis, where he nightly took ineffable delight in gazing upon great masses of gold. Avaricious people gathered proof of this when they looked at the eyes of the good man, to which the yellow metal seemed to have conveyed its tints. The glance of a man accustomed to draw enormous interest from his capital acquires, like that of the libertine, the gambler, or the sycophant, certain indefinable habits,--furtive, eager, mysterious movements, which never escape the notice of his co-religionists. This secret language is in a certain way the freemasonry of the passions. Monsieur Grandet inspired the respectful esteem due to one who owed no man anything, who, skilful cooper and experienced wine-grower that he was, guessed with the precision of an astronomer whether he ought to manufacture a thousand puncheons for his vintage, or only five hundred, who never failed in any speculation, and always had casks for sale when casks were worth more than the commodity that filled them, who could store his whole vintage in his cellars and bide his time to put the puncheons on the market at two hundred francs, when the little proprietors had been forced to sell theirs for five louis. His famous vintage of 1811, judiciously stored and slowly disposed of, brought him in more than two hundred and forty thousand francs. Financially speaking, Monsieur Grandet was something between a tiger and a boa-constrictor. He could crouch and lie low, watch his prey a long while, spring upon it, open his jaws, swallow a mass of louis, and then rest tranquilly like a snake in process of digestion, impassible, methodical, and cold. No one saw him pass without a feeling of admiration mingled with respect and fear; had not every man in Saumur felt the rending of those polished steel claws? For this one, Maitre Cruchot had procured the money required for the purchase of a domain, but at eleven per cent. For that one, Monsieur des Grassins discounted bills of exchange, but at a frightful deduction of interest. Few days ever passed that Monsieur Grandet’s name was not mentioned either in the markets or in social conversations at the evening gatherings. To some the fortune of the old wine-grower was an object of patriotic pride. More than one merchant, more than one innkeeper, said to strangers with a certain complacency: “Monsieur, we have two or three millionaire establishments; but as for Monsieur Grandet, he does not himself know how much he is worth.” In 1816 the best reckoners in Saumur estimated the landed property of the worthy man at nearly four millions; but as, on an average, he had made yearly, from 1793 to 1817, a hundred thousand francs out of that property, it was fair to presume that he possessed in actual money a sum nearly equal to the value of his estate. So that when, after a game of boston or an evening discussion on the matter of vines, the talk fell upon Monsieur Grandet, knowing people said: “Le Pere Grandet? le Pere Grandet must have at least five or six millions.” “You are cleverer than I am; I have never been able to find out the amount,” answered Monsieur Cruchot or Monsieur des Grassins, when either chanced to overhear the remark. If some Parisian mentioned Rothschild or Monsieur Lafitte, the people of Saumur asked if he were as rich as Monsieur Grandet. When the Parisian, with a smile, tossed them a disdainful affirmative, they looked at each other and shook their heads with an incredulous air. So large a fortune covered with a golden mantle all the actions of this man. If in early days some peculiarities of his life gave occasion for laughter or ridicule, laughter and ridicule had long since died away. His least important actions had the authority of results repeatedly shown. His speech, his clothing, his gestures, the blinking of his eyes, were law to the country-side, where every one, after studying him as a naturalist studies the result of instinct in the lower animals, had come to understand the deep mute wisdom of his slightest actions. “It will be a hard winter,” said one; “Pere Grandet has put on his fur gloves.” “Pere Grandet is buying quantities of staves; there will be plenty of wine this year.” Monsieur Grandet never bought either bread or meat. His farmers supplied him weekly with a sufficiency of capons, chickens, eggs, butter, and his tithe of wheat. He owned a mill; and the tenant was bound, over and above his rent, to take a certain quantity of grain and return him the flour and bran. La Grande Nanon, his only servant, though she was no longer young, baked the bread of the household herself every Saturday. Monsieur Grandet arranged with kitchen-gardeners who were his tenants to supply him with vegetables. As to fruits, he gathered such quantities that he sold the greater part in the market. His fire-wood was cut from his own hedgerows or taken from the half-rotten old sheds which he built at the corners of his fields, and whose planks the farmers carted into town for him, all cut up, and obligingly stacked in his wood-house, receiving in return his thanks. His only known expenditures were for the consecrated bread, the clothing of his wife and daughter, the hire of their chairs in church, the wages of la Grand Nanon, the tinning of the saucepans, lights, taxes, repairs on his buildings, and the costs of his various industries. He had six hundred acres of woodland, lately purchased, which he induced a neighbor’s keeper to watch, under the promise of an indemnity. After the acquisition of this property he ate game for the first time. Monsieur Grandet’s manners were very simple. He spoke little. He usually expressed his meaning by short sententious phrases uttered in a soft voice. After the Revolution, the epoch at which he first came into notice, the good man stuttered in a wearisome way as soon as he was required to speak at length or to maintain an argument. This stammering, the incoherence of his language, the flux of words in which he drowned his thought, his apparent lack of logic, attributed to defects of education, were in reality assumed, and will be sufficiently explained by certain events in the following history. Four sentences, precise as algebraic formulas, sufficed him usually to grasp and solve all difficulties of life and commerce: “I don’t know; I cannot; I will not; I will see about it.” He never said yes, or no, and never committed himself to writing. If people talked to him he listened coldly, holding his chin in his right hand and resting his right elbow in the back of his left hand, forming in his own mind opinions on all matters, from which he never receded. He reflected long before making any business agreement. When his opponent, after careful conversation, avowed the secret of his own purposes, confident that he had secured his listener’s assent, Grandet answered: “I can decide nothing without consulting my wife.” His wife, whom he had reduced to a state of helpless slavery, was a useful screen to him in business. He went nowhere among friends; he neither gave nor accepted dinners; he made no stir or noise, seeming to economize in everything, even movement. He never disturbed or disarranged the things of other people, out of respect for the rights of property. Nevertheless, in spite of his soft voice, in spite of his circumspect bearing, the language and habits of a coarse nature came to the surface, especially in his own home, where he controlled himself less than elsewhere. Physically, Grandet was a man five feet high, thick-set, square-built, with calves twelve inches in circumference, knotted knee-joints, and broad shoulders; his face was round, tanned, and pitted by the small-pox; his chin was straight, his lips had no curves, his teeth were white; his eyes had that calm, devouring expression which people attribute to the basilisk; his forehead, full of transverse wrinkles, was not without certain significant protuberances; his yellow-grayish hair was said to be silver and gold by certain young people who did not realize the impropriety of making a jest about Monsieur Grandet. His nose, thick at the end, bore a veined wen, which the common people said, not without reason, was full of malice. The whole countenance showed a dangerous cunning, an integrity without warmth, the egotism of a man long used to concentrate every feeling upon the enjoyments of avarice and upon the only human being who was anything whatever to him,--his daughter and sole heiress, Eugenie. Attitude, manners, bearing, everything about him, in short, testified to that belief in himself which the habit of succeeding in all enterprises never fails to give to a man. Thus, though his manners were unctuous and soft outwardly, Monsieur Grandet’s nature was of iron. His dress never varied; and those who saw him to-day saw him such as he had been since 1791. His stout shoes were tied with leathern thongs; he wore, in all weathers, thick woollen stockings, short breeches of coarse maroon cloth with silver buckles, a velvet waistcoat, in alternate stripes of yellow and puce, buttoned squarely, a large maroon coat with wide flaps, a black cravat, and a quaker’s hat. His gloves, thick as those of a gendarme, lasted him twenty months; to preserve them, he always laid them methodically on the brim of his hat in one particular spot. Saumur knew nothing further about this personage. Only six individuals had a right of entrance to Monsieur Grandet’s house. The most important of the first three was a nephew of Monsieur Cruchot. Since his appointment as president of the Civil courts of Saumur this young man had added the name of Bonfons to that of Cruchot. He now signed himself C. de Bonfons. Any litigant so ill-advised as to call him Monsieur Cruchot would soon be made to feel his folly in court. The magistrate protected those who called him Monsieur le president, but he favored with gracious smiles those who addressed him as Monsieur de Bonfons. Monsieur le president was thirty-three years old, and possessed the estate of Bonfons (Boni Fontis), worth seven thousand francs a year; he expected to inherit the property of his uncle the notary and that of another uncle, the Abbe Cruchot, a dignitary of the chapter of Saint-Martin de Tours, both of whom were thought to be very rich. These three Cruchots, backed by a goodly number of cousins, and allied to twenty families in the town, formed a party, like the Medici in Florence; like the Medici, the Cruchots had their Pazzi. Madame des Grassins, mother of a son twenty-three years of age, came assiduously to play cards with Madame Grandet, hoping to marry her dear Adolphe to Mademoiselle Eugenie. Monsieur des Grassins, the banker, vigorously promoted the schemes of his wife by means of secret services constantly rendered to the old miser, and always arrived in time upon the field of battle. The three des Grassins likewise had their adherents, their cousins, their faithful allies. On the Cruchot side the abbe, the Talleyrand of the family, well backed-up by his brother the notary, sharply contested every inch of ground with his female adversary, and tried to obtain the rich heiress for his nephew the president. This secret warfare between the Cruchots and des Grassins, the prize thereof being the hand in marriage of Eugenie Grandet, kept the various social circles of Saumur in violent agitation. Would Mademoiselle Grandet marry Monsieur le president or Monsieur Adolphe des Grassins? To this problem some replied that Monsieur Grandet would never give his daughter to the one or to the other. The old cooper, eaten up with ambition, was looking, they said, for a peer of France, to whom an income of three hundred thousand francs would make all the past, present, and future casks of the Grandets acceptable. Others replied that Monsieur and Madame des Grassins were nobles, and exceedingly rich; that Adolphe was a personable young fellow; and that unless the old man had a nephew of the pope at his beck and call, such a suitable alliance ought to satisfy a man who came from nothing,--a man whom Saumur remembered with an adze in his hand, and who had, moreover, worn the _bonnet rouge_. Certain wise heads called attention to the fact that Monsieur Cruchot de Bonfons had the right of entry to the house at all times, whereas his rival was received only on Sundays. Others, however, maintained that Madame des Grassins was more intimate with the women of the house of Grandet than the Cruchots were, and could put into their minds certain ideas which would lead, sooner or later, to success. To this the former retorted that the Abbe Cruchot was the most insinuating man in the world: pit a woman against a monk, and the struggle was even. “It is diamond cut diamond,” said a Saumur wit. The oldest inhabitants, wiser than their fellows, declared that the Grandets knew better than to let the property go out of the family, and that Mademoiselle Eugenie Grandet of Saumur would be married to the son of Monsieur Grandet of Paris, a wealthy wholesale wine-merchant. To this the Cruchotines and the Grassinists replied: “In the first place, the two brothers have seen each other only twice in thirty years; and next, Monsieur Grandet of Paris has ambitious designs for his son. He is mayor of an arrondissement, a deputy, colonel of the National Guard, judge in the commercial courts; he disowns the Grandets of Saumur, and means to ally himself with some ducal family,--ducal under favor of Napoleon.” In short, was there anything not said of an heiress who was talked of through a circumference of fifty miles, and even in the public conveyances from Angers to Blois, inclusively! At the beginning of 1811, the Cruchotines won a signal advantage over the Grassinists. The estate of Froidfond, remarkable for its park, its mansion, its farms, streams, ponds, forests, and worth about three millions, was put up for sale by the young Marquis de Froidfond, who was obliged to liquidate his possessions. Maitre Cruchot, the president, and the abbe, aided by their adherents, were able to prevent the sale of the estate in little lots. The notary concluded a bargain with the young man for the whole property, payable in gold, persuading him that suits without number would have to be brought against the purchasers of small lots before he could get the money for them; it was better, therefore, to sell the whole to Monsieur Grandet, who was solvent and able to pay for the estate in ready money. The fine marquisate of Froidfond was accordingly conveyed down the gullet of Monsieur Grandet, who, to the great astonishment of Saumur, paid for it, under proper discount, with the usual formalities. This affair echoed from Nantes to Orleans. Monsieur Grandet took advantage of a cart returning by way of Froidfond to go and see his chateau. Having cast a master’s eye over the whole property, he returned to Saumur, satisfied that he had invested his money at five per cent, and seized by the stupendous thought of extending and increasing the marquisate of Froidfond by concentrating all his property there. Then, to fill up his coffers, now nearly empty, he resolved to thin out his woods and his forests, and to sell off the poplars in the meadows"

In [7]:
text1=" The Marquise de Mascaret is a woman of high society who is known for her beauty and her wealth. She is also known for her love of gambling and her wild parties. She has a daughter, Yvette, who is just as beautiful and just as wild as her mother. Yvette is the main attraction of the Marquise's parties and she is courted by many men. However, no one knows for sure who will be the lucky man to capture her heart."

In [351]:
text_places='''Salons Paris Bohemia Haut-Mississippi the Rue de Barrie America Indies Italy the Rue Royale'''

In [413]:
long_summary= '''Jean de Servigny and Leon Saval were friends since college. They were walking on the boulevard after dinner. Jean suggested that they walk instead of taking a cab because the weather was fine. They walked slowly, smoking cigars and talking. They had been friends for a long time and were very close. Jean was a small, slender man with a bald head and a mustache. He was very athletic and was known for his wit, his fortune, and his connections. Leon was a tall, handsome man  The Marquise de Mascaret is a woman of high society who is known for her beauty and her wealth. She is also known for her love of gambling and her wild parties. She has a daughter, Yvette, who is just as beautiful and just as wild as her mother. Yvette is the main attraction of the Marquise's parties and she is courted by many men. However, no one knows for sure who will be the lucky man to capture her heart. Servigny was a man who was in love with a woman named Clotilde. He was very attracted to her, but he knew that he could never marry her because of her mother's reputation. He was also jealous of her and didn't know if she was a good person or not. He thought that she might have had many lovers, but he also thought that she might be innocent. He was confused about her and didn't know what to do. The Marquise de Mascaret is a wealthy woman who lives in a house that is frequented by many lovers. Her daughter, Yvette, is a young woman who is not interested in marriage. Servigny, a friend of the Marquise, believes that Yvette will eventually become a courtesan. He plans to introduce his friend, Count Saval, to the Marquise and her daughter. Servigny and Saval are going to a party. Servigny is a duke but Saval is not. Servigny wants to introduce Saval as the Vice-Roi du 'Haut-Mississippi' but Saval refuses. They arrive at the party and the master of ceremonies announces them as the Duke de Servigny and the Baron Saval. The mistress of the house is very beautiful and has a charming voice. Servigny and Saval, two friends, went to a party hosted by the Duke. The Duke's wife, a beautiful woman with a slight mustache, welcomed them. Servigny introduced Saval to her. She told Servigny that her daughter was in the other parlor. Servigny took Saval to the other parlor, where they saw a group of women dancing. Suddenly, a tall girl came running towards them. She was the Duke's daughter. She was very beautiful and had a The story starts with a description of a young woman, Yvette, who is talking to a man named Servigny. She asks him if he dances, and they waltz together. They dance very fast and furiously, and they seem to be in a trance. The other dancers stop to watch them, and everyone applauds when they finish.
After the dance, Yvette tells Servigny that he is like a tiger about to spring upon his prey. She takes his arm and they walk away The Marquise de Mascaret, accompanied by her daughter Yvette, arrived at the Chateau de Servigny. Yvette was very flirtatious and enjoyed teasing Servigny, who was very much in love with her. The Marquise invited Servigny and Saval, a friend of Servigny, to dinner the following Saturday and to stay over Sunday. Yvette said that she and Servigny would commit a lot of follies in the country and that they would set all the world by the ears. Servigny and Saval entered the casino. Servigny introduced Saval to Yvette, his last adorer. Yvette nicknamed Saval "M. Colossus of Rhodes, Junior". Servigny teased Yvette and she left them quickly. Servigny took Saval to the gambling-room. Servigny asked Saval if he wanted to join the game, but Saval declined. They left the casino.'''

In [42]:
summaryy= "The text depicts the melancholic ambiance of old houses in provincial towns, comparing them to somber settings like cloisters, moorlands, and ruins. It introduces Monsieur Grandet, a wealthy and miserly man residing in Saumur. He owns various properties and vineyards and is admired yet feared for his avarice. The narrative delves into his character, highlighting his financial acumen, speech patterns, and control over his daughter Eugenie. Two rival factions, the Cruchot family and the des Grassins, compete for influence over Grandet and Eugenie's potential marriage. The acquisition of the Froidfond estate further showcases Grandet's increasing wealth. Despite his riches, Grandet remains a mysterious figure to the townspeople. The narrative sets the stage for conflicts and power struggles among the characters."

# **YAKE**

In [418]:
language = "en"
max_ngram_size = 3
deduplication_threshold = 0.2
deduplication_algo = 'seqm'
windowSizes = 1
numOfKeywords = 20

In [419]:
custom_kw_extractor = yake.KeywordExtractor(lan=language, n=max_ngram_size, dedupLim=deduplication_threshold, dedupFunc=deduplication_algo, windowsSize=windowSize, top=numOfKeywords, features=None)
keywords = custom_kw_extractor.extract_keywords(long_summary)

keyword_list=[kw[0]for kw in keywords]

keyword_list

['Servigny',
 'Yvette',
 'Marquise',
 'woman',
 'Leon Saval',
 'college',
 'wild',
 'thought',
 'dinner',
 'named',
 'cab',
 'small',
 'attraction',
 'lucky',
 'Haut-Mississippi',
 'plans',
 'stop',
 'watch',
 'good person']

# **NER**

**identify and classify named entities in the chapter text**

- PERSON: Names of people, including first names, last names, and titles.
- NORP: Nationalities, religious or political groups.
- FAC: Buildings, airports, highways, bridges, etc.
- ORG: Companies, organizations, institutions, etc.
- GPE: Geopolitical entities, countries, cities, states.
- LOC: Non-GPE locations, mountain ranges, bodies of water.
- PRODUCT: Objects, vehicles, foods, etc. (not services).
- EVENT: Named hurricanes, battles, wars, sports events, etc.
- WORK_OF_ART: Titles of books, songs, etc.
- LAW: Named documents made into laws, laws, etc.
- LANGUAGE: Any named language.
- DATE: Absolute or relative dates or periods.
- TIME: Times smaller than a day.
- PERCENT: Percentage, including "%".
- MONEY: Monetary values, including unit.
- QUANTITY: Measurements, as of weight or distance.
- ORDINAL: "first", "second", etc.
- CARDINAL: Numerals that do not fall under other types.

In [371]:


# Load the pre-trained NER model
nlp = spacy.load('en_core_web_md')


# Process the text with spaCy's NER model
doc = nlp(text_full)
persons_list=[]
places_list=[]
actions_list=[]
for ent in doc.ents:
    if ent.label_== "PERSON" and ent.text not in persons_list:
        persons_list.append(f'{ent.text}')
    elif ent.label_ in ["LOC","FAC","GPE"] and ent.text not in places_list:
        places_list.append(f'{ent.text}')
    elif ent.label_ =="EVENT" and ent.text not in actions_list:
        actions_list.append(f'{ent.text}')

In [372]:
actions_list

['the Champs-Elysees']

# POS

- ADJ: Adjective
- ADP: Adposition (preposition or postposition)
- ADV: Adverb
- AUX: Auxiliary verb
- CONJ: Coordinating conjunction
- CCONJ: Coordinating conjunction
- DET: Determiner
- INTJ: Interjection
- NOUN: Noun
- NUM: Numeral
- PART: Particle
- PRON: Pronoun
- PROPN: Proper noun
- PUNCT: Punctuation
- SCONJ: Subordinating conjunction
- SYM: Symbol
- VERB: Verb
- X: Other (uncategorized)
- SPACE: Space (for whitespace)

In [79]:
nlp = spacy.load('en_core_web_md')

In [134]:
doc = nlp(text)

In [379]:
doc = nlp(text_full)
actions_pos_list=[]
persons=[]
places=[]
mood_list=[]
for token in doc:
    if token.pos_== 'VERB' and token not in actions_pos_list:
        actions_pos_list.append(token)
    elif token.pos_== 'PROPN' and token not in persons:
        persons.append(token)
    elif token.pos_== 'NOUN' and token not in places:
        places.append(token)
    elif token.pos_ in ['ADJ'] and token not in mood_list:
        mood_list.append(token)

In [380]:
mood_list

[fine,
 restless,
 peculiar,
 little,
 hurrying,
 red,
 blue,
 green,
 thin,
 dark,
 clear,
 rapid,
 yellow,
 slow,
 mild,
 close,
 devoted,
 firm,
 small,
 bald,
 frail,
 curled,
 bright,
 fine,
 tireless,
 languid,
 strong,
 slight,
 gymnastic,
 cold,
 hot,
 nervous,
 artificial,
 fashionable,
 peculiar,
 certain,
 true,
 Parisian,
 light,
 sceptical,
 changeable,
 captivating,
 energetic,
 capable,
 selfish,
 generous,
 Indifferent,
 passionate,
 conflicting,
 own,
 shrewd,
 rich,
 superb,
 colossal,
 handsome,
 tall,
 big,
 strong,
 little,
 countless,
 omnibus,
 little,
 perplexed,
 charming,
 real,
 first,
 first,
 last,
 last,
 lovable,
 bold,
 free,
 free,
 suspicious,
 various,
 formidable,
 criminal,
 compliant,
 dishonest,
 social,
 unknown,
 slightest,
 dangerous,
 false,
 brave,
 own,
 interesting,
 amusing,
 witty,
 commonplace,
 ordinary,
 French,
 pretty,
 little,
 foreign,
 past,
 fine,
 glorious,
 true,
 unwholesome,
 irresistible,
 old,
 rapacious,
 true,
 elegant,
 good,
 feline,
 vicious,
 good,
 fashionable,
 marvel,
 dear,
 principal,
 Tall,
 magnificent,
 ripe,
 old,
 fair,
 dark,
 merry,
 ready,
 ready,
 mad,
 lucky,
 better,
 complete,
 marvelous,
 infamy,
 calm,
 profligate,
 artless,
 Strange,
 magnificent,
 noble,
 great,
 grand,
 same,
 serious,
 little,
 long,
 thirsty,
 skillful,
 irrational,
 possible,
 reasonable,
 probable,
 abnormal,
 natural,
 exquisite,
 detestable,
 third,
 few,
 possible,
 asleep,
 grave,
 physical,
 strongest,
 monstrous,
 little,
 jealous,
 jealous,
 ignorant,
 incomprehensible,
 charming,
 wretched,
 indiscreet,
 modest,
 spotless,
 artless,
 chaste,
 certain,
 same,
 impeccable,
 private,
 many,
 other,
 great,
 new,
 random,
 strange,
 literary,
 hasty,
 peculiar,
 young,
 strange,
 general,
 certain,
 other,
 certain,
 first,
 simple,
 less,
 possible,
 bad,
 high,
 common,
 young,
 common,
 rapid,
 probable,
 possible,
 young,
 inevitable,
 many,
 Italian,
 best,
 several,
 less,
 rich,
 less,
 astounding,
 such,
 decent,
 best,
 respectable,
 gentle,
 giant,
 Silent,
 dark,
 low,
 other,
 important,
 shameful,
 fictitious,
 plain,
 capable,
 stupid,
 only,
 common,
 worse,
 better,
 obstinate,
 possible,
 monstrous,
 Roi,
 much,
 more,
 foolish,
 certain,
 fine,
 modern,
 warm,
 composed,
 continuous,
 adjoining,
 tall,
 erect,
 wide,
 serious,
 white,
 short,
 haughty,
 loud,
 first,
 first,
 bare,
 brilliant,
 majestic,
 narrow,
 low,
 glossy,
 black,
 little,
 tall,
 large,
 little,
 stout,
 ripe,
 heavy,
 warm,
 potent,
 full,
 captivating,
 enormous,
 black,
 little,
 narrow,
 large,
 seductive,
 greatest,
 natural,
 light,
 clear,
 physical,
 flexible,
 pretty,
 red,
 open,
 little,
 other,
 welcome,
 brilliant,
 slightest,
 upper,
 darker,
 pleasant,
 Other,
 other,
 good,
 fleeting,
 pleased,
 fleshly,
 fresh,
 good,
 new,
 right,
 lower,
 young,
 legitimate,
 curious,
 moral,
 young,
 joint,
 little,
 left,
 second,
 serious,
 good,
 slender,
 more,
 tall,
 long,
 left,
 quick,
 little,
 white,
 golden,
 white,
 red,
 fiery,
 little,
 thin,
 natural,
 noble,
 simple,
 moral,
 physical,
 Good,
 tall,
 greatest,
 young,
 comic,
 little,
 medium,
 quick,
 erect,
 motionless,
 invisible,
 other,
 mad,
 little,
 flushed,
 strange,
 ardent,
 timid,
 less,
 daring,
 troubled,
 blue,
 black,
 natural,
 giddy,
 poor,
 steadier,
 short,
 long,
 ordinary,
 fashionable,
 mental,
 different,
 dear,
 following,
 serene,
 big,
 black,
 charmed,
 naive,
 traitorous,
 mad,
 little,
 many,
 close,
 long,
 frank,
 arid,
 careless,
 funny,
 funny,
 frank,
 more,
 right,
 extraordinary,
 ignorant,
 such,
 haughty,
 vulgar,
 several,
 individual,
 thin,
 brown,
 easy,
 constrained,
 less,
 less,
 less,
 tall,
 stout,
 gray,
 loud,
 devoted,
 last,
 big,
 fat,
 rich,
 stupid,
 veritable,
 major,
 bigger,
 interesting,
 other,
 preoccupied,
 soft,
 many,
 bad,
 friendly,
 solemn,
 perfect,
 good,
 latest,
 serious,
 superb,
 superb,
 dear,
 little,
 green,
 human,
 various,
 odd,
 same,
 severe,
 different,
 stiff,
 haughty,
 open,
 black,
 huge,
 Austrian,
 Russian,
 armed,
 twisted,
 ready,
 quieter,
 many,
 interesting,
 best,
 such,
 dear,
 ordinary,
 bake,
 real,
 charming,
 sous,
 sous,
 latest,
 English,
 common,
 free,
 better,
 serious,
 same,
 commonplace,
 amusing,
 same,
 different,
 sous,
 much,
 younger,
 stupid,
 nondescript,
 few,
 same,
 good,
 first,
 good]

In [383]:
import yake
import spacy

def chapter_topic_creation(text):
    # Running the Yake
    language = "en"
    max_ngram_sizes = 3
    deduplication_thresholds = 0.1
    deduplication_algos = ['seqm']
    windowSizes = 1
    numOfKeywords = 100
    
    custom_kw_extractor = yake.KeywordExtractor(lan=language, n=max_ngram_size, dedupLim=deduplication_threshold, dedupFunc=deduplication_algo, windowsSize=windowSize, top=numOfKeywords, features=None)
    keywords = custom_kw_extractor.extract_keywords(text)

    keyword_list=[kw[0]for kw in keywords]
    
    # Applying the NER on the Keyword_list
    texto= ' '.join(keyword_list)
    # Load the pre-trained NER model
    nlp = spacy.load('en_core_web_md')
    
    # Process the text with spaCy's NER model
    doc = nlp(texto)
    persons_list=[]
    places_list=[]
    actions_mood_list=[]
    for ent in doc.ents:
        if ent.label_== "PERSON" and ent.text not in persons_list:
            persons_list.append(f'{ent.text}')
        elif ent.label_ in ["LOC","FAC","GPE"] and ent.text not in places_list:
            places_list.append(f'{ent.text}')
        elif ent.label_ =="EVENT" and ent.text not in actions_mood_list:
            actions_mood_list.append(f'{ent.text}')
       
    # Apply POS on the keyword_list
    for token in doc:
        if token.pos_== 'VERB' and token.text not in actions_mood_list:
            actions_mood_list.append(token.text)
        elif token.pos_=='PROPN' and token.text not in persons_list:
            persons_list.append(token.text)
        elif token.pos_== 'NOUN'and token.text not in places_list:
            places_list.append(token.text)
        elif token.pos_ in ['ADJ'] and token.text not in actions_mood_list:
            actions_mood_list.append(token.text)
            
    
    topic_dict={}
    topic_dict['persons']= persons_list
    topic_dict['places']= places_list
    topic_dict['action_and_mood']= actions_mood_list
    
    topic_df = pd.DataFrame({key: pd.Series(value) for key, value in topic_dict.items()}) 
    
    return topic_df

In [415]:
topic_dict= chapter_topic_creation(long_summary)

In [416]:
import pandas as pd
topic_df = pd.DataFrame({key: pd.Series(value) for key, value in topic_dict.items()})

In [417]:
topic_df

           persons            places action_and_mood
0  Yvette Marquise  Haut-Mississippi         thought
1       Leon Saval             woman           named
2         Servigny           college           small
3           Yvette            dinner           lucky
4         Marquise               cab            stop
5             Leon        attraction           watch
6            Saval             plans            good
7             wild            person             NaN
8             Haut               NaN             NaN
9      Mississippi               NaN             NaN

## **NEW FUNCTION ON THE FINAL SUMMARiES**

In [75]:
def chapter_topic_creation_2(text_full,summary):
    persons_list_2=[]
    places_list_2=[]
    
    # Load the pre-trained NER model
    nlp = spacy.load('en_core_web_md')
    
    # Process the text with spaCy's NER model
    doc = nlp(summary)
    
    for ent in doc.ents:
        if ent.label_== "PERSON" and ent.text not in persons_list_2:
            persons_list_2.append(f'{ent.text}')
    
    # Apply POS on the keyword_list
    doc2 = nlp(text_full)
    for ent in doc2.ents:
        if ent.label_ in ["LOC","FAC","GPE"] and ent.text not in places_list_2:
            places_list_2.append(f'{ent.text}')
            
    # Running the Yake
    language = "en"
    max_ngram_size = 3
    deduplication_threshold= 0.2
    deduplication_algo= 'seqm'
    windowSize = 1
    numOfKeywords = 10
    
    custom_kw_extractor = yake.KeywordExtractor(lan=language, n=max_ngram_size, dedupLim=deduplication_threshold, dedupFunc=deduplication_algo, windowsSize=windowSize, top=numOfKeywords, features=None)
    keywords = custom_kw_extractor.extract_keywords(summary)

    keyword_list=[kw[0]for kw in keywords if kw[0] not in persons_list_2 and places_list_2]
        
    
    
    topic_dict_2={}
    topic_dict_2['persons']= persons_list_2
    topic_dict_2['places']= places_list_2
    topic_dict_2['general']= keyword_list
    
    return topic_dict_2

In [76]:
topic_dict_2=chapter_topic_creation_2(text,summaryy)

In [77]:
topic_dict_2

{'persons': ['Monsieur Grandet', 'Eugenie', 'Cruchot', 'Froidfond', 'Grandet'],
 'places': ['Saumur',
  'Old',
  'France',
  'Touraine',
  'the French Republic',
  'Grandet',
  'Empire',
  'louis',
  'boston',
  'Florence',
  'beck',
  'Paris',
  'Nantes',
  'Orleans'],
 'general': ['provincial towns',
  'text depicts',
  'melancholic ambiance',
  'houses in provincial',
  'residing in Saumur',
  'moorlands',
  'somber',
  'narrative',
  'admired yet feared']}

In [26]:
import pandas as pd
topic_dict_2=chapter_topic_creation_2(text_full,text1)
pd.DataFrame({key: pd.Series(value) for key, value in topic_dict_2.items()})

    persons             places               general
0    Yvette             Salons         woman of high
1  Marquise              Paris          high society
2        de            Bohemia  Marquise de Mascaret
3  Mascaret   Haut-Mississippi                Yvette
4       NaN  the Rue de Barrie                beauty
5       NaN            America                  wild
6       NaN             Indies                  love
7       NaN              Italy              gambling
8       NaN     the Rue Royale             lucky man
9       NaN                NaN            attraction

# **Filtering down similar texts**

['Yvette Marquise de Mascaret',
 'Salons Paris Bohemia Haut-Mississippi the Rue de Barrie America Indies Italy the Rue Royale',
 'woman of high high society Marquise de Mascaret Yvette beauty wild love gambling lucky man attraction']

In [453]:
all_topic_pairs = list(combinations(result, 2))
similar_topic = []
for pair in all_topic_pairs:
    topic1 = nlp(pair[0])
    topic2 = nlp(pair[1])
    similarity = topic1.similarity(topic2)
    if similarity > 0.8:
        similar_topic.append(pair)

In [65]:
topic_dict_2['general']

['provincial towns',
 'text depicts',
 'melancholic ambiance',
 'residing in Saumur',
 'moorlands',
 'somber',
 'narrative',
 'admired yet feared',
 'Cruchot']

In [62]:

import spacy
from itertools import combinations




# def pre_process(titles):
#     """
#     Pre-processes titles by removing stopwords and lemmatizing text.
#     :param titles: list of strings, contains target titles,.
#     :return: preprocessed_title_docs, list containing pre-processed titles.
#     """

#     # Preprocess all the titles
#     title_docs = [nlp(x) for x in titles]
#     preprocessed_title_docs = []
#     lemmatized_tokens = []
#     for title_doc in title_docs:
#         for token in title_doc:
#             if not token.is_stop:
#                 lemmatized_tokens.append(token.lemma_)
#         preprocessed_title_docs.append(" ".join(lemmatized_tokens))
#         del lemmatized_tokens[
#             :
#             ]  # empty the lemmatized tokens list as the code moves onto a new title

#     return preprocessed_title_docs

def similarity_filter(topics):
    """
    Recursively check if titles pass a similarity filter.
    :param titles: list of strings, contains titles.
    If the function finds titles that fail the similarity test, the above param will be the function output.
    :return: this method upon itself unless there are no similar titles; in that case the feed that was passed
    in is returned.
    """

   
    nlp = spacy.load('en_core_web_md')
    # Remove similar titles
    all_topic_pairs = list(combinations(topics, 2))
    similar_topic = []
    for pair in all_topic_pairs:
        topic1 = nlp(pair[0])
        topic2 = nlp(pair[1])
        similarity = topic1.similarity(topic2)
        if similarity > 0.8:
            similar_topic.append(pair)

    topic_to_remove = []
    for a_topic in similar_topic:
        # Get the index of the first title in the pair
        index_for_removal = topics.index(a_topic[0])
        topic_to_remove.append(index_for_removal)

    # Get indices of similar titles and remove them
    similar_topic_counts = set(topic_to_remove)
    similar_topic = [
        x[1] for x in enumerate(topics) if x[0] in similar_topic_counts
    ]

    # Exit the recursion if there are no longer any similar titles
    if len(similar_topic_counts) == 0:
        return topics

    # Continue the recursion if there are still titles to remove
    else:
        # Remove similar titles from the next input
        for topic in similar_topic:
            idx = topics.index(topic)
            topics.pop(idx)
            
        return similarity_filter(topics)

In [64]:
similarity_filter(topic_dict_2['general'])

['provincial towns',
 'text depicts',
 'melancholic ambiance',
 'residing in Saumur',
 'moorlands',
 'somber',
 'narrative',
 'admired yet feared',
 'Cruchot']

## . Result prompting the boss
1. The setting is in Saumur, a town in the Loire Valley in France.
2. The main character is Monsieur Grandet, a wealthy wine merchant.
3. Monsieur Grandet is a widower with one daughter, Eugenie.
4. Monsieur Grandet is extremely wealthy and miserly.
5. Monsieur Grandet is considering marrying off his daughter to a wealthy man in order to increase his fortune.